spring:
  application:
    name: ai-tunnel-web
server:
  port: ${PORT:5000}
logging:
  level:
    root: ERROR
app: 
  rate-limit:
    duration: 10s # refill interval duration
    capacity: 10 # number of requests before throttling
  environment: test
  parameter-names:
    openAiApiKeyPath: "/openai/${spring.application.name}/${app.environment}/api-key"
openai:
  chat: GPT_4_O_MINI
---
spring:
  config:
    activate:
      on-profile: test
---
spring:
  config:
    activate:
      on-profile: prod
app:
  environment: prod
  